name: sync

on:
  schedule:
    # Runs every two hours" (see https://crontab.guru)
    - cron: '0 */2 * * *'
  workflow_dispatch:
  

jobs:
  sync:
    name: sync
    runs-on: ubuntu-latest
    steps:
      - name: Install trakplexsync
        run: pipx install PlexTraktSync

      - name: Add secrets to config
        run: |
          mkdir -p /home/runner/.config/PlexTraktSync
          cd /home/runner/.config/PlexTraktSync
          echo "${{ secrets.ENVFILE }}" >> .env
          echo "${{ secrets.SERVERS }}" >> servers.yml
      
      - name: create-json
        id: create-json
        uses: schdck/create-env-json@v1
        with:
         name: .pytrakt.json
         super-secret: ${{ secrets.PYTRAKT }}
      - name: sync
        run: |
          cp ${{ steps.create-env.outputs.full-path }} /home/runner/.config/PlexTraktSync/.pytrakt.json 
          plextraktsync sync